FROM golang:1.14

MAINTAINER Marian Zlatev

# create a build dir
RUN mkdir /build
WORKDIR /build

# download dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

# copy the project itself
COPY . .

CMD ["go", "test", "-v", "./..."]