FROM golang:1.14.6-alpine3.12

MAINTAINER Marian Zlatev

# create a build dir
RUN mkdir /build
WORKDIR /build

# it seems gcc is not available on plain alpine
ENV CGO_ENABLED=0

# download dependencies
COPY go.mod .
COPY go.sum .
RUN go mod download

# copy the project itself
COPY . .

CMD ["go", "test", "-v", "./..."]